### ISSUE TITLE
Pinecone  npm run ingest gives 429 error

### ISSUE THREAD

**Issue by lkh9908** [ucl98/gpt4_langchain_pdf-detailed-walktrough#1]
c:\Users\KaihaoLiu\Desktop\AI\onepdf\gpt4-pdf-chatbot-langchain\scripts\ingest-data.ts:46
    throw new Error('Failed to ingest your data');
          ^

Error: Failed to ingest your dataError: Request failed with status code 429
    at run (c:\Users\KaihaoLiu\Desktop\AI\onepdf\gpt4-pdf-chatbot-langchain\scripts\ingest-data.ts:46:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at <anonymous> (c:\Users\KaihaoLiu\Desktop\AI\onepdf\gpt4-pdf-chatbot-langchain\scripts\ingest-data.ts:51:3)

Node.js v18.14.0

The pdf is extremely short, what is the problem here

**Comment by alessandrosantospirito** [comment]
Reade the debugging section. I would think that your openai acccount is not configured correctly/ you don't have a valid payment option.
